### PR TITLE
added possibility to change styles of input

### PR DESCRIPTION
**Pull request by wtfil**
Hi!
First of all, thank you for material input.
I found few things which could be better:
- `style` property may be useful for overwriting such things as color and fontSize
- new props should update state of component

### CODE REVIEW

**Comment by philipshurpik** [comment]
Hi!

I have added support of properties: `wrapperStyle, inputStyle, labelStyle` to be able to change styles of all components in field.
Also added possibility to change input and label fontSize from corresponding styles.

And reformatted code - to use 2 spaces in all files :)    
If you like another formatting - please note - I will change )  
But now it's really more comfortable to look at and contribute in project )

**Comment by evblurbs** [comment]
I apologize for the delayed response! I like the additions here!

Since I've done a poor job of updating it (I should be watching this repo more regularly now that I'm using it myself more), there are a number of conflicts with this pull request. Some of them have already been addressed:

* @wtfil the prop value is now updating with https://github.com/evblurbs/react-native-md-textinput/commit/dabd78031d2ddd2170df559857d73025f88065ba and https://github.com/evblurbs/react-native-md-textinput/commit/e0a91dc62764f552a4635d0acaa83b1ed63cc4ba
* @philipshurpik I fixed the indenting :) That was my fault - due to switching editors.

I like the idea of being able to customize the styles. My first pass was to just follow the Material Design guidelines strictly. I'll add that methods and update this thread accordingly.

**Comment by evblurbs** [comment]
I've added the props `inputStyle`, `wrapperStyle`, and `labelStyle`. Thanks @wtfil and @philipshurpik for your help!

I've also added the props `textColor`, `textFocusColor`, and `textBlurColor` to provide more control of the TextInput color.

I'll look into the other updates made here later.

**Comment by wtfil** [comment]
Closing since this is not relevant any more :)

**Pull request closed without merging**
